version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "poetry run"
    command: "gunicorn -w 4 wsgi:flask_app -b 0.0.0.0:5000"
    restart: always
    ports:
     - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - ENV=${ENV}
      - LOG_FILE=logs.log
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - LIMITER_STORAGE_URI=redis://redis

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "poetry run"
    command: "celery -A make_celery worker --loglevel=info"
    restart: always
    environment:
      - MONGODB_HOST=host.docker.internal
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - ENV=${ENV}
      - LOG_FILE=logs.log
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis
      - LIMITER_STORAGE_URI=redis://redis
    links:
      - redis
    depends_on:
      - redis

  redis:
      image: redis
      restart: "always"
